### ISSUE TITLE
[FEATURE REQUEST] Running container in foreground

### ISSUE THREAD

**Issue by hron84** [shiwaforce/poco#54]
Currently, `poco up plan` always start containers behind the scenes. In some cases it would be more useful, if the container could be started in foreground, like how the `docker-compose up` works.

**Comment by sarkiroka** [comment]
@hron84 
Could you give one or more specific example(s) of where this would be useful?

**Comment by hron84** [comment]
I currently have a Git repository with Nagios configuration files and I use docker-compose to create a Nagios container with same version as the production and check the configuration files (I don't want to actually run a Nagios server, since it's not neccessary and could not work because a whole different networking conditions. I just want to check configuration files from syntax, and dependency aspect).

The docker-compose.yml:

```
version: "3.7"

services:
  nagios:
    image: jasonrivers/nagios:latest
    volumes:
      - .:/opt/nagios/etc/
    command: /opt/nagios/bin/nagios -v /opt/nagios/etc/nagios.cfg
```

After starting the tests, Nagios runs a few checks and exits. If the Nagios encounter any problems it logs to the standard output/standard error streams. But since I cannot see immediately the output of the output of the container, I lose the information about why the tests are failed. Running `poco log` after starting not helps, these tests are very quick and the container become stopped right after that, `poco log` mosty displays nothing/errors from this.

I know there is a workaround for this problem but since docker-compose itself already supports running multiple containers in the foreground I just can't see why PoCo cannot do the same.
